const translations = {
    sk: {
        "nav-home": "Domov",
        "nav-services": "Služby",
        "nav-approach": "Náš prístup",
        "nav-pricing": "Cenník",
        "nav-contact": "Kontakt",
        "nav-cta": "Objednať",
        "hero-title": "Tvoríme weby, <br>ktoré posúvajú váš <br> biznis vpred.",
        "hero-desc": "Vytvárame moderné, rýchle a pútavé webové riešenia na mieru, ktoré pomáhajú vášmu podnikaniu rásť.",
        "hero-cta": "Objednať konzultáciu zadarmo",
        "services-tag": "Čo robíme",
        "services-title": "Komplexné riešenia pre váš digitálny úspech",
        "services-desc": "Od prvotného nápadu až po finálne spustenie. Navrhujeme a vyvíjame weby, ktoré prinášajú reálne výsledky.",
        "s1-title": "Webstránky na mieru",
        "s1-desc": "Moderný, rýchly a responzívny dizajn prispôsobený vašim potrebám a cieľovej skupine.",
        "s2-title": "E-shopy & Rýchly predaj",
        "s2-desc": "Výkonné internetové obchody s jednoduchou správou produktov a bezpečným platobným systémom.",
        "s3-title": "SEO & Výkonnostný marketing",
        "s3-desc": "Optimalizácia pre vyhľadávače (Google), aby vás zákazníci našli na prvých priečkach.",
        "s4-title": "Redizajn & Správa webu",
        "s4-desc": "Osvieženie starého webu do moderného šatu, pravidelné aktualizácie, údržba a bezpečnosť.",
        "approach-tag": "Ako pracujeme",
        "approach-title": "Jednoduchý proces k vášmu novému webu",
        "approach-desc": "Prevádzame vás celým procesom krok za krokom, bez zbytočného technického žargónu.",
        "step1-title": "Konzultácia & Stratégia",
        "step1-desc": "Spoznáme vaše podnikanie, ciele a cieľovú skupinu. Definujeme rozsah projektu a pripravíme jasný plán.",
        "step2-title": "Dizajn & UX",
        "step2-desc": "Vytvoríme vizuálny návrh na mieru s dôrazom na estetiku, prehľadnosť a zážitok návštevníka.",
        "step3-title": "Vývoj & Testovanie",
        "step3-desc": "Návrh premeníme na čistý, rýchly a responzívny kód. Dôkladne otestujeme funkčnosť na všetkých zariadeniach.",
        "step4-title": "Spustenie & Podpora",
        "step4-desc": "Web nasadíme na vašu doménu, zaškolíme vás do obsluhy a zostávame vám k dispozícii pre ďalší rozvoj.",
        "pricing-tag": "Transparentný cenník",
        "pricing-title": "Investícia do vášho rastu",
        "pricing-desc": "Žiadne skryté poplatky. Vyberte si balík tvorby webu a úroveň mesačnej starostlivosti.",
        "p1-name": "Starter",
        "p1-desc": "Ideálne pre malé podniky, živnostníkov a efektívne landing page stránky.",
        "p1-period": "jednorazovo",
        "p1-f1": "Jednostránkový web (Landing Page)",
        "p1-f2": "Moderný responzívny dizajn",
        "p1-f3": "Základné SEO nastavenie",
        "p1-f4": "Kontaktný formulár & Google Mapy",
        "p1-f5": "Rýchle načítanie & SSL certifikát",
        "p1-btn": "Vybrať Starter",
        "p2-badge": "Najobľúbenejšie",
        "p2-name": "Business",
        "p2-desc": "Kompletný firemný web na mieru navrhnutý na prilákanie a konverziu zákazníkov.",
        "p2-period": "jednorazovo",
        "p2-f1": "Všetko, čo je v Starter balíku",
        "p2-f2": "Až 8 podstránok na mieru",
        "p2-f3": "Podpora viacerých jazykov (EN / SK)",
        "p2-f4": "Integrácia Google Analytics",
        "p2-f5": "Základné zaškolenie do CMS & podpora",
        "p2-btn": "Vybrať Business",
        "p3-name": "E-Commerce",
        "p3-desc": "Výkonný internetový obchod vytvorený na bezproblémový predaj vašich produktov.",
        "p3-period": "jednorazovo",
        "p3-f1": "Kompletné nastavenie online obchodu",
        "p3-f2": "Platobné brány & integrácia dopravy",
        "p3-f3": "Správa produktov & kategórií",
        "p3-f4": "Automatické faktúry & transakčné e-maily",
        "p3-f5": "Optimalizácia konverzného pomeru",
        "p3-btn": "Vybrať E-Commerce",
        "pricing-custom-note": "Každý projekt je jedinečný a jeho rozsah sa môže líšiť, čomu prispôsobujeme aj finálnu cenu. U nás máte vždy <strong>presnú a konečnú cenu projektu stanovenú ešte pred začatím prác</strong>. Bez vášho výslovného potvrdenia tejto sumy na projekte nezačneme pracovať a vy tak <strong>neplatíte absolútne nič</strong>.",
        "care-tag": "Mesačná starostlivosť",
        "care-title": "Správa a údržba webu",
        "care-desc": "Nechajte technické záležitosti na nás a sústreďte sa plne na vaše podnikanie.",
        "m-period": "/ mesiac",
        "m1-name": "Basic Care",
        "m1-desc": "Pre webstránky, ktoré vyžadujú stabilný hosting, bezpečnosť a plynulý chod.",
        "m1-f1": "Rýchly Webhosting & SSL v cene",
        "m1-f2": "Pravidelné mesačné zálohy",
        "m1-f3": "Aktualizácia systému a pluginov",
        "m1-f4": "Bezpečnostný monitoring 24/7",
        "m1-f5": "E-mailová podpora",
        "m1-btn": "Vybrať Basic Care",
        "m2-badge": "Odporúčané",
        "m2-name": "Pro Care",
        "m2-desc": "Ideálne pre firmy, ktoré potrebujú pravidelne aktualizovať obsah a texty na webe.",
        "m2-f1": "Všetko z balíka Basic Care",
        "m2-f2": "Týždenné zálohovanie dát",
        "m2-f3": "<strong>Až 2 hodiny úprav obsahu</strong> mesačne",
        "m2-f4": "Prednostné riešenie požiadaviek",
        "m2-f5": "Mesačný prehľad návštevnosti",
        "m2-btn": "Vybrať Pro Care",
        "m3-name": "Premium Care",
        "m3-desc": "Kompletný outsourcing digitálnej správy vrátane SEO úprav a prioritnej podpory.",
        "m3-f1": "Všetko z balíka Pro Care",
        "m3-f2": "Denné zálohovanie dát",
        "m3-f3": "<strong>Až 4 hodiny úprav obsahu</strong> mesačne",
        "m3-f4": "Mesačný SEO & Výkonnostný audit",
        "m3-f5": "Garantovaná podpora do 24 hodín",
        "m3-btn": "Vybrať Premium Care",
        "contact-tag": "Ozvite sa",
        "contact-title": "Vybudujme spoločne niečo skvelé.",
        "contact-desc": "Máte na mysli nejaký projekt alebo chcete prediskutovať, ako môžeme pomôcť vašej firme rásť? Pošlite nám správu.",
        "contact-email-title": "Email",
        "contact-phone-title": "Zavolajte nám",
        "contact-hours-title": "Pracovné hodiny",
        "contact-hours-val": "Pondelok - Piatok: 9:00 - 18:00",
        "form-label-name": "Vaše meno",
        "form-placeholder-name": "Nick",
        "form-label-email": "Váš email",
        "form-placeholder-email": "nick@example.com",
        "form-label-package": "Otázka alebo záujem o",
        "opt-general": "Všeobecná otázka",
        "opt-starter": "Starter (£350 jednorazovo)",
        "opt-business": "Business (£1,100 jednorazovo)",
        "opt-ecommerce": "E-Commerce (£2,100 jednorazovo)",
        "opt-custom": "Riešenie na mieru / Iné",
        "opt-basic-care": "Basic Care (£35 / mesiac)",
        "opt-pro-care": "Pro Care (£75 / mesiac)",
        "opt-premium-care": "Premium Care (£140 / mesiac)",
        "form-label-message": "Vaša správa",
        "form-placeholder-message": "Napíšte nám viac o...",
        "form-btn-submit": "Poslať správu",
        "footer-desc": "Navrhujeme a vyvíjame moderné webové stránky a e-shopy na mieru, ktoré menia návštevníkov na platiacich zákazníkov.",
        "footer-nav-title": "Navigácia",
        "footer-services-title": "Služby",
        "footer-contact-title": "Kontakt",
        "footer-contact-desc": "Máte otázky alebo záujem o spoluprácu?",
        "footer-rights": "© 2026 abcweb.ing. Všetky práva vyhradené.",
        "footer-privacy": "Ochrana osobných údajov",
        "footer-terms": "Všeobecné podmienky",
        // Prreklad obchodných podmienok
        "legal-tag": "Právne informácie",
        "terms-main-title": "Všeobecné obchodné podmienky",
        "terms-main-desc": "Platné a účinné pre služby poskytované prostredníctvom abcweb.ing.",
        "terms-provider-title": "Poskytovateľ služieb:",
        "t1-title": "1. Úvodné ustanovenia",
        "t1-p1": "1.1. Tieto Všeobecné obchodné podmienky (ďalej len „VOP“) upravujú právne vzťahy medzi prevádzkovateľom webu abcweb.ing (ďalej len „poskytovateľ“) a objednávateľom služieb (ďalej len „klient“).",
        "t1-p2": "1.2. Službami sa rozumie vývoj webových stránok, e-shopov, riešení na mieru, SEO optimalizácia, správcovské a údržbové služby (balíky Basic Care, Pro Care, Premium Care) a súvisiace konzultácie.",
        "t2-title": "2. Objednávka a vznik zmluvy",
        "t2-p1": "2.1. Klient si môže služby objednať prostredníctvom kontaktného formulára na webe, e-mailom alebo telefonicky.",
        "t2-p2": "2.2. Zmluvný vzťah vzniká písomným potvrdením objednávky a dohodnutím rozsahu prác a finálnej ceny (e-mailom) zo strany poskytovateľa aj klienta.",
        "t3-title": "3. Ceny a platobné podmienky",
        "t3-p1": "3.1. Ceny jednorazových balíkov (Starter, Business, E-Commerce) aj mesačných služieb (Basic Care, Pro Care, Premium Care) sú uvedené v cenníku na webstránke v mene GBP (£).",
        "t3-p2": "3.2. Pri tvorbe webstránok a e-shopov má klient vždy vopred stanovenú presnú a konečnú cenu projektu ešte pred začatím prác. Bez výslovného schválenia tejto sumy klientom sa práce nezačnú a klient neplatí žiadne poplatky.",
        "t3-p3": "3.3. Platba prebieha na základe vystavenej faktúry so splatnosťou uvedenou na faktúre, zvyčajne bankovým prevodom.",
        "t3-p4": "3.4. Pri mesačných balíkoch údržby sa platba uhrádza vopred na nasledujúce fakturačné obdobie (mesiac).",
        "t4-title": "4. Práva a povinnosti strán",
        "t4-sub1": "4.1. Poskytovateľ sa zaväzuje:",
        "t4-l1": "Dodať dielo / službu v dohodnutom rozsahu, kvalite a termíne.",
        "t4-l2": "Zachovávať mlčanlivosť o dôverných informáciách a dodaných podkladoch klienta.",
        "t4-sub2": "4.2. Klient sa zaväzuje:",
        "t4-l3": "Poskytnúť potrebnú súčinnosť (dodať texty, podklady, logá, prístupy), ktoré sú nevyhnutné pre realizáciu diela.",
        "t4-l4": "Uhradiť dohodnutú cenu za dodané služby v lehote splatnosti.",
        "t5-title": "5. Autorské práva a odovzdanie diela",
        "t5-p1": "5.1. Majetkové autorské práva k vytvorenej webstránke / grafike prechádzajú na klienta v momente úplného uhradenia dohodnutej zmluvnej ceny.",
        "t5-p2": "5.2. Poskytovateľ si vyhradzuje právo uviesť dokončený projekt ako referenciu vo svojom portfóliu (ak nie je písomne dohodnuté inak).",
        "t6-title": "6. Trvanie a ukončenie zmluvy (Mesačné balíky)",
        "t6-p1": "6.1. Balíky mesačnej starostlivosti (Basic, Pro, Premium Care) sa dojednávajú na dobu neurčitú.",
        "t6-p2": "6.2. Klient aj poskytovateľ môžu mesačnú starostlivosť kedykoľvek vypovedať k koncu aktuálne predplateného obdobia bez storno poplatkov.",
        "t7-title": "7. Zodpovednosť za škodu a reklamácie",
        "t7-p1": "7.1. Poskytovateľ zodpovedá za funkčnosť dodaného webu v rozsahu dohodnutej špecifikácie.",
        "t7-p2": "7.2. Poskytovateľ nezodpovedá za výpadky alebo nefunkčnosť spôsobenú zásahom tretej strany, nesprávnym používaním zo strany klienta alebo výpadkami externých služieb (hosting tretích strán, platobné brány a pod.).",
        "t7-p3": "7.3. Reklamácie a opravy prípadných chýb je potrebné nahlásiť e-mailom na info@abcweb.ing. Poskytovateľ sa zaväzuje nahlásené nedostatky odstrániť v čo najkratšom možnom čase.",
        "t8-title": "8. Záverečné ustanovenia",
        "t8-p1": "8.1. Tieto VOP nadobúdajú platnosť dňom ich zverejnenia na webstránke abcweb.ing.",
        "t8-p2": "8.2. Poskytovateľ si vyhradzuje právo na zmenu týchto VOP. O zmene bude klientov informovať zverejnením aktualizovaného znenia na webe.",
        // GDPR & Ochrana osobných údajov
        "footer-privacy": "Ochrana osobných údajov",
        "privacy-tag": "GDPR & Súkromie",
        "privacy-main-title": "Ochrana osobných údajov",
        "privacy-main-desc": "Informácie o tom, ako spracúvame a chráníme vaše osobné údaje.",
        "privacy-controller-title": "Prevádzkovateľ osobných údajov:",
        "p1-title": "1. Aké údaje zbierame a prečo",
        "p1-p1": "Osobné údaje spracúvame výhradne v rozsahu nezbytnom pre poskytovanie našich služieb a komunikáciu s vami. Ide najmä o:",
        "p1-l1": "Kontaktné údaje: Meno, e-mailová adresa, telefónne číslo (získané z kontaktného formulára alebo e-mailovej komunikácie) na účely odpovede na vaše dopyty a plnenia zmluvy.",
        "p1-l2": "Fakturačné údaje: Meno, adresa, IČO/DIČ, bankové údaje na účely vystavovania faktúr a účtovníctva.",
        "p2-title": "2. Právny základ spracúvania",
        "p2-p1": "Vaše údaje spracúvame na základe:",
        "p2-l1": "Plnenia zmluvy alebo predsudmluvných vzťahov: Spracovanie dopytu, vypracovanie cenovej ponuky, realizácia projektu.",
        "p2-l2": "Plnenia zákonných povinností: Vystavovanie a archivácia daňových a účtovných dokladov.",
        "p2-l3": "Oprávneného záujmu: Ochrana našich práv a evidencia komunikácie.",
        "p3-title": "3. Doba uchovávania údajov",
        "p3-p1": "Osobné údaje uchovávame len po dobu nevyhnutnú na naplnenie účelu spracovania:",
        "p3-l1": "Údaje z kontaktného formulára uchovávame po dobu trvania komunikácie alebo platnosti zmluvného vzťahu.",
        "p3-l2": "Účtovné doklady uchovávame po dobu stanovenú príslušnými právnymi predpismi (spravidla 10 rokov).",
        "p4-title": "4. Poskytovanie údajov tretím stranám",
        "p4-p1": "Vaše údaje nepredávame ani neposkytujeme tretím stranám na marketingové účely. Pre zabezpečenie chodu služieb využívame overených sprostredkovateľov:",
        "p4-l1": "Poskytovatelia hostingových a e-mailových služieb.",
        "p4-l2": "Poskytovateľ formulárovej služby (FormSubmit pre doručovanie správ).",
        "p4-l3": "Externí účtovníci a správcovia softvéru.",
        "p5-title": "5. Vaše práva podľa GDPR",
        "p5-p1": "V súvislosti s vašimi osobnými údajmi máte nasledovné práva:",
        "p5-l1": "Právo na prístup k svojim osobným údajom.",
        "p5-l2": "Právo na opravu nesprávnych alebo neúplných údajov.",
        "p5-l3": "Právo na výmaz (právo „na zabudnutie“), ak neexistuje zákonný dôvod na ich uchovávanie.",
        "p5-l4": "Právo na obmedzenie spracúvania a právo namietať proti spracúvaniu.",
        "p5-l5": "Právo podať sťažnosť na dozorný orgán pre ochranu osobných údajov.",
        "p6-title": "6. Kontakt pre otázky",
        "p6-p1": "Ak máte akékoľvek otázky týkajúce sa spracúvania vašich osobných údajov, kontaktujte nás na e-mailovej adrese info@abcweb.ing."

    },
    en: {
        "nav-home": "Home",
        "nav-services": "Services",
        "nav-approach": "Our Approach",
        "nav-pricing": "Pricing",
        "nav-contact": "Contact",
        "nav-cta": "Order",
        "hero-title": "WEBSITES <BR> THAT MOVE YOUR BUSINESS <BR> FORWARD.",
        "hero-desc": "We build modern, fast, and engaging custom web solutions that help your business grow.",
        "hero-cta": "Book Free Consultation",
        "services-tag": "What We Do",
        "services-title": "Comprehensive Solutions for Your Digital Success",
        "services-desc": "From initial concept to final launch. We design and develop websites that drive real results.",
        "s1-title": "Custom Websites",
        "s1-desc": "Modern, fast, and responsive design tailored to your needs and target audience.",
        "s2-title": "E-Commerce & Quick Sales",
        "s2-desc": "Powerful online stores with easy product management and secure payment integration.",
        "s3-title": "SEO & Performance Marketing",
        "s3-desc": "Search engine optimization (Google) to get your business ranked on top.",
        "s4-title": "Redesign & Management",
        "s4-desc": "Revitalize your old website into a modern look with regular updates, maintenance, and security.",
        "approach-tag": "How We Work",
        "approach-title": "A Simple Process to Your New Website",
        "approach-desc": "We guide you through the whole process step by step, without unnecessary technical jargon.",
        "step1-title": "Consultation & Strategy",
        "step1-desc": "We learn about your business, goals, and audience to define project scope and a clear plan.",
        "step2-title": "Design & UX",
        "step2-desc": "We create a custom visual design focused on aesthetics, clarity, and user experience.",
        "step3-title": "Development & Testing",
        "step3-desc": "We turn the design into clean, fast, and responsive code. Fully tested across all devices.",
        "step4-title": "Launch & Support",
        "step4-desc": "We deploy the website to your domain, train you on maintenance, and stay available for growth.",
        "pricing-tag": "Transparent Pricing",
        "pricing-title": "Investment in Your Growth",
        "pricing-desc": "No hidden fees. Choose a web development package and a level of monthly maintenance.",
        "p1-name": "Starter",
        "p1-desc": "Ideal for small businesses, freelancers, and high-converting landing pages.",
        "p1-period": "one-off",
        "p1-f1": "Single-page Website (Landing Page)",
        "p1-f2": "Modern responsive design",
        "p1-f3": "Basic SEO setup",
        "p1-f4": "Contact form & Google Maps",
        "p1-f5": "Fast loading & SSL certificate",
        "p1-btn": "Choose Starter",
        "p2-badge": "Most Popular",
        "p2-name": "Business",
        "p2-desc": "A complete custom corporate website designed to attract and convert customers.",
        "p2-period": "one-off",
        "p2-f1": "Everything in Starter plan",
        "p2-f2": "Up to 8 custom pages",
        "p2-f3": "Multi-language support (EN / SK)",
        "p2-f4": "Google Analytics integration",
        "p2-f5": "Basic CMS training & support",
        "p2-btn": "Choose Business",
        "p3-name": "E-Commerce",
        "p3-desc": "Powerful online store built to seamlessly sell your products online.",
        "p3-period": "one-off",
        "p3-f1": "Full online store setup",
        "p3-f2": "Payment gateways & shipping integration",
        "p3-f3": "Product & category management",
        "p3-f4": "Automated invoices & emails",
        "p3-f5": "Conversion rate optimization",
        "p3-btn": "Choose E-Commerce",
        "pricing-custom-note": "Every project is unique and its scope may vary, which is reflected in the final price. With us, you will always get an <strong>exact and fixed project quote before any work begins</strong>. Without your explicit confirmation of this amount, we will not start the project, meaning <strong>you pay absolutely nothing</strong>.",
        "care-tag": "Monthly Care",
        "care-title": "Website Maintenance & Support",
        "care-desc": "Leave the technical details to us and focus entirely on growing your business.",
        "m-period": "/ month",
        "m1-name": "Basic Care",
        "m1-desc": "For websites requiring fast hosting, security, and smooth operation.",
        "m1-f1": "Fast Web Hosting & SSL included",
        "m1-f2": "Regular monthly backups",
        "m1-f3": "System & plugin updates",
        "m1-f4": "24/7 Security monitoring",
        "m1-f5": "Email support",
        "m1-btn": "Choose Basic Care",
        "m2-badge": "Recommended",
        "m2-name": "Pro Care",
        "m2-desc": "Ideal for businesses needing regular monthly content and text updates.",
        "m2-f1": "Everything in Basic Care",
        "m2-f2": "Weekly data backups",
        "m2-f3": "<strong>Up to 2 hours of content edits</strong> per month",
        "m2-f4": "Priority task handling",
        "m2-f5": "Monthly traffic overview",
        "m2-btn": "Choose Pro Care",
        "m3-name": "Premium Care",
        "m3-desc": "Full digital management outsourcing including SEO tweaks and priority support.",
        "m3-f1": "Everything in Pro Care",
        "m3-f2": "Daily data backups",
        "m3-f3": "<strong>Up to 4 hours of content edits</strong> per month",
        "m3-f4": "Monthly SEO & Performance audit",
        "m3-f5": "Guaranteed support within 24 hours",
        "m3-btn": "Choose Premium Care",
        "contact-tag": "Get in Touch",
        "contact-title": "Let's build something great together.",
        "contact-desc": "Have a project in mind or want to discuss how we can help your business grow? Send us a message.",
        "contact-email-title": "Email",
        "contact-phone-title": "Call Us",
        "contact-hours-title": "Working Hours",
        "contact-hours-val": "Monday - Friday: 9:00 - 18:00",
        "form-label-name": "Your Name",
        "form-placeholder-name": "Nick",
        "form-label-email": "Your Email",
        "form-placeholder-email": "nick@example.com",
        "form-label-package": "Subject or Interest",
        "opt-general": "General Inquiry",
        "opt-starter": "Starter (£350 one-off)",
        "opt-business": "Business (£1,100 one-off)",
        "opt-ecommerce": "E-Commerce (£2,100 one-off)",
        "opt-custom": "Custom Project / Other",
        "opt-basic-care": "Basic Care (£35 / month)",
        "opt-pro-care": "Pro Care (£75 / month)",
        "opt-premium-care": "Premium Care (£140 / month)",
        "form-label-message": "Your Message",
        "form-placeholder-message": "Tell us more about your project...",
        "form-btn-submit": "Send Message",
        "footer-desc": "We design and build modern custom websites and e-shops that turn visitors into paying customers.",
        "footer-nav-title": "Navigation",
        "footer-services-title": "Services",
        "footer-how-we-work": "How we work",
        "footer-price-title": "Price list",
        "footer-contact-title": "Contact",
        "footer-contact-desc": "Have questions or interested in working together?",
        "footer-rights": "© 2026 abcweb.ing. All rights reserved.",
        "footer-privacy": "Privacy Policy",
        "footer-terms": "Terms & Conditions",
        // translation of terms and conditions
        "legal-tag": "Legal Information",
        "terms-main-title": "Terms and Conditions",
        "terms-main-desc": "Valid and effective for services provided via abcweb.ing.",
        "terms-provider-title": "Service Provider:",
        "t1-title": "1. General Provisions",
        "t1-p1": "1.1. These Terms and Conditions (hereinafter referred to as 'Terms') govern the legal relationships between the operator of abcweb.ing (hereinafter 'provider') and the client.",
        "t1-p2": "1.2. Services include web development, e-commerce stores, custom solutions, SEO optimization, maintenance services (Basic Care, Pro Care, Premium Care), and related consulting.",
        "t2-title": "2. Orders and Contract Formation",
        "t2-p1": "2.1. The client can order services via the website contact form, email, or phone.",
        "t2-p2": "2.2. A contractual agreement is established upon written order confirmation and mutual agreement on the project scope and final price via email.",
        "t3-title": "3. Pricing and Payment Terms",
        "t3-p1": "3.1. Prices for one-off packages (Starter, Business, E-Commerce) and monthly care packages (Basic Care, Pro Care, Premium Care) are stated on the website in GBP (£).",
        "t3-p2": "3.2. For website and e-commerce projects, the client always receives a fixed and final quote prior to work commencement. No work begins and no fees apply without explicit client approval.",
        "t3-p3": "3.3. Payments are processed via invoice with the due date specified on the document, typically via bank transfer.",
        "t3-p4": "3.4. Monthly maintenance plans are billed in advance for the upcoming billing cycle (month).",
        "t4-title": "4. Rights and Obligations",
        "t4-sub1": "4.1. The provider agrees to:",
        "t4-l1": "Deliver the work/service within the agreed scope, quality, and timeframe.",
        "t4-l2": "Maintain strict confidentiality regarding client data and provided materials.",
        "t4-sub2": "4.2. The client agrees to:",
        "t4-l3": "Provide necessary cooperation (text content, logos, credentials) required for project completion.",
        "t4-l4": "Pay the agreed price for delivered services by the invoice due date.",
        "t5-title": "5. Copyright and Handover",
        "t5-p1": "5.1. Economic copyrights for created websites/graphics transfer to the client upon full payment of the agreed price.",
        "t5-p2": "5.2. The provider reserves the right to display completed projects as portfolio references unless agreed otherwise in writing.",
        "t6-title": "6. Duration and Termination (Monthly Plans)",
        "t6-p1": "6.1. Monthly maintenance plans (Basic, Pro, Premium Care) are contracted on an indefinite basis.",
        "t6-p2": "6.2. Both parties may terminate monthly care plans at any time prior to the end of the currently paid billing period without cancellation fees.",
        "t7-title": "7. Liability and Complaints",
        "t7-p1": "7.1. The provider is liable for proper web functionality within the agreed specification.",
        "t7-p2": "7.2. The provider is not liable for outages caused by third parties, improper client usage, or external service downtime (third-party hosting, payment gateways, etc.).",
        "t7-p3": "7.3. Complaints must be reported via email to info@abcweb.ing. The provider commits to resolving reported issues promptly.",
        "t8-title": "8. Final Provisions",
        "t8-p1": "8.1. These Terms come into effect upon publication on the abcweb.ing website.",
        "t8-p2": "8.2. The provider reserves the right to modify these Terms, notifying clients via updated website postings.",
        // Privacy Policy
        "footer-privacy": "Privacy Policy",
        "privacy-tag": "GDPR & Privacy",
        "privacy-main-title": "Privacy Policy",
        "privacy-main-desc": "Information on how we process and protect your personal data.",
        "privacy-controller-title": "Data Controller:",
        "p1-title": "1. Data We Collect and Why",
        "p1-p1": "We process personal data solely to the extent necessary to provide our services and communicate with you, including:",
        "p1-l1": "Contact details: Name, email address, phone number (collected via contact form or email) to answer inquiries and fulfill contracts.",
        "p1-l2": "Billing details: Name, address, registration/VAT IDs, bank details for invoicing and accounting purposes.",
        "p2-title": "2. Legal Basis for Processing",
        "p2-p1": "We process your data based on:",
        "p2-l1": "Contract performance or pre-contractual steps: Processing inquiries, preparing quotes, completing projects.",
        "p2-l2": "Legal compliance: Issuing and archiving tax and accounting documents.",
        "p2-l3": "Legitimate interest: Protecting our legal rights and maintaining business records.",
        "p3-title": "3. Data Retention Period",
        "p3-p1": "We retain personal data only for as long as necessary to fulfill the purpose of processing:",
        "p3-l1": "Contact form submissions are kept for the duration of communication or active contractual relationships.",
        "p3-l2": "Accounting documents are retained as required by applicable laws (typically 10 years).",
        "p4-title": "4. Sharing Data with Third Parties",
        "p4-p1": "We do not sell or share your data for marketing purposes. We work with trusted processors to operate our services:",
        "p4-l1": "Hosting and email service providers.",
        "p4-l2": "Form delivery service providers (FormSubmit for contact messages).",
        "p4-l3": "External accountants and software administrators.",
        "p5-title": "5. Your Rights Under GDPR",
        "p5-p1": "Under GDPR regulations, you have the following rights:",
        "p5-l1": "The right to access your personal data.",
        "p5-l2": "The right to rectify inaccurate or incomplete data.",
        "p5-l3": "The right to erasure ('right to be forgotten') when no legal obligation mandates retention.",
        "p5-l4": "The right to restrict or object to data processing.",
        "p5-l5": "The right to lodge a complaint with a supervisory data protection authority.",
        "p6-title": "6. Contact Information",
        "p6-p1": "If you have any questions regarding the processing of your personal data, please contact us at info@abcweb.ing."
    }
};

function setLanguage(lang) {
    const dict = translations[lang];
    if (!dict) return;

    // 1. Zmena textu všetkých prvkov podľa data-key
    const elements = document.querySelectorAll('[data-key]');
    elements.forEach(el => {
        const key = el.getAttribute('data-key');
        if (dict[key] !== undefined) {
            el.innerHTML = dict[key];
        }
    });

    // 2. Zmena placeholderov podľa data-key-placeholder
    const placeholders = document.querySelectorAll('[data-key-placeholder]');
    placeholders.forEach(el => {
        const key = el.getAttribute('data-key-placeholder');
        if (dict[key] !== undefined) {
            el.placeholder = dict[key];
        }
    });

    // 3. Zmena aktívneho tlačidla SK / EN
    const buttons = document.querySelectorAll('.lang-btn');
    buttons.forEach(btn => {
        if (btn.textContent.trim().toLowerCase() === lang.toLowerCase()) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }
    });

    localStorage.setItem('selected_lang', lang);
}

// Spustenie pri načítaní
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selected_lang') || 'sk';
    setLanguage(savedLang);

    // Mobilné menu
    const menuToggle = document.querySelector('.menu-toggle');
    const navLinks = document.querySelector('.nav-links');
    if (menuToggle && navLinks) {
        menuToggle.addEventListener('click', () => {
            navLinks.classList.toggle('open');
        });
    }
});